server:
  port: 9600
spring:
  application:
    name: user-center
  cloud:
    nacos:
      discovery:
        server-addr: 123.57.129.60:8848
  profiles:
    active: dev

feign:
  okhttp:
    enabled: true
