spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://123.57.129.60:3307/db_car?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: 123456
      hikari:
        # 是客户端等待连接池连接的最大毫秒数
        connection-timeout: 30000
        # 是允许连接在连接池中空闲的最长时间
        minimum-idle: 10
        # 配置最大池大小
        maximum-pool-size: 65
        # 是允许连接在连接池中空闲的最长时间（以毫秒为单位）
        idle-timeout: 60000
        # 池中连接关闭后的最长生命周期（以毫秒为单位）
        max-lifetime: 600000
        # 配置从池返回的连接的默认自动提交行为。默认值为true。
        auto-commit: true
        # 连接池的名称
        pool-name: conmmuty-floor-hikaricp
        # 开启连接监测泄露
        leak-detection-threshold: 5000
        # 测试连接数据库
        connection-test-query: SELECT 1


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
pagehelper:
  #  分页参数合理化
  reasonable: true